version: '3.4'

x-common-variables: &common-variables
  ZEEBE_ADDRESS: zeebe-zeebe-gateway:26500
  KAFKA_ADDRESS: b-1.boehmerkafkacluster.r9zvn9.c3.kafka.eu-central-1.amazonaws.com:9092,b-2.boehmerkafkacluster.r9zvn9.c3.kafka.eu-central-1.amazonaws.com:9092


services:
  kafkazeebeconnector:
    image: l3oehmer/kafkazeebeconnector
    container_name: kafkazeebeconnector
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
  worker1:
    image: l3oehmer/worker1
    container_name: worker1
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
      - "443"
  worker2:
    image: l3oehmer/worker2
    container_name: worker2
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
      - "443"
  worker3:
    image: l3oehmer/worker3
    container_name: worker3
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
  worker4:
    image: l3oehmer/worker4
    container_name: worker4
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
      - "443"
  worker5:
    image: l3oehmer/worker5
    container_name: worker5
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
      - "443"
  worker6:
    image: l3oehmer/worker6
    container_name: worker6
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
  worker7:
    image: l3oehmer/worker7
    container_name: worker7
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
      - "443"
  workeri1:
    image: l3oehmer/workeri1
    container_name: workeri1
    environment: *common-variables
    ports:
      - "26500"
      - "9092"
  workeri2:
    image: l3oehmer/workeri2
    container_name: workeri2
    environment: *common-variables
    ports:
      - "26500"
      - "9092"