apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: workeri1
  name: workeri1
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: workeri1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: workeri1
    spec:
      containers:
        - env:
            - name: KAFKA_ADDRESS
              value: b-1.boehmerkafkacluster.id3u3z.c3.kafka.eu-central-1.amazonaws.com:9092,b-2.boehmerkafkacluster.id3u3z.c3.kafka.eu-central-1.amazonaws.com:9092
            - name: ZEEBE_ADDRESS
              value: zeebe-zeebe-gateway:26500
          image: l3oehmer/workeri1
          name: workeri1
          ports:
            - containerPort: 26500
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
status: {}
